// MainPageCardData.js
// Shared card data for filtering

const contentTypes = ["Case", "Lecture", "Live"];

const cardData = [
  {
    id: 1,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/01.jpg",
    vimeoId: "824804225",
    contentType: "Case",
    duration: "12:34",
    daysAgo: 5,
  },
  {
    id: 2,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/02.jpg",
    vimeoId: "824804225",
    contentType: "Lecture",
    duration: "09:21",
    daysAgo: 2,
  },
  {
    id: 3,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "824804225",
    contentType: "Live",
    duration: "15:10",
    daysAgo: 10,
  },
  {
    id: 4,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/05.jpg",
    vimeoId: "824804225",
    contentType: "Case",
    duration: "10:00",
    daysAgo: 1,
  },
  {
    id: 5,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/07.jpg",
    vimeoId: "824804225",
    contentType: "Lecture",
    duration: "12:00",
    daysAgo: 3,
  },
  {
    id: 6,
    type: "ACL",
    category: "Knee",
    level: "Advanced",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "1094906074",
    contentType: "Live",
    duration: "15:00",
    daysAgo: 7,
  },
  {
    id: 7,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/01.jpg",
    vimeoId: "824804225",
    contentType: "Case",
    duration: "11:00",
    daysAgo: 4,
  },
  {
    id: 8,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/02.jpg",
    vimeoId: "824804225",
    contentType: "Lecture",
    duration: "08:00",
    daysAgo: 1,
  },
  {
    id: 9,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "1094906074",
    contentType: "Live",
    duration: "14:00",
    daysAgo: 8,
  },
  {
    id: 10,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/05.jpg",
    vimeoId: "1094906074",
    contentType: "Case",
    duration: "10:00",
    daysAgo: 2,
  },
  {
    id: 11,
    type: "ACL",
    category: "Knee",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/07.jpg",
    vimeoId: "824804225",
    contentType: "Lecture",
    duration: "11:00",
    daysAgo: 3,
  },
  {
    id: 12,
    type: "ACL",
    category: "Knee",
    level: "Advanced",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "824804225",
    contentType: "Live",
    duration: "15:00",
    daysAgo: 6,
  },
  {
    id: 13,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/01.jpg",
    vimeoId: "824804225",
    contentType: "Case",
    duration: "10:00",
    daysAgo: 1,
  },
  {
    id: 14,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/02.jpg",
    vimeoId: "824804225",
    contentType: "Lecture",
    duration: "09:00",
    daysAgo: 2,
  },
  {
    id: 15,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "",
    contentType: "Live",
    duration: "12:00",
    daysAgo: 5,
  },
  {
    id: 16,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/05.jpg",
    vimeoId: "824804225",
    contentType: "Case",
    duration: "11:00",
    daysAgo: 3,
  },
  {
    id: 17,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/07.jpg",
    vimeoId: "1094906074",
    contentType: "Lecture",
    duration: "10:00",
    daysAgo: 1,
  },
  {
    id: 18,
    type: "Disc",
    category: "Hip",
    level: "Advanced",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "1099892481",
    contentType: "Live",
    duration: "14:00",
    daysAgo: 7,
  },
  {
    id: 19,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/01.jpg",
    vimeoId: "1094906074",
    contentType: "Case",
    duration: "10:00",
    daysAgo: 2,
  },
  {
    id: 20,
    type: "Disc",
    category: "Hip",
    level: "Advanced",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/02.jpg",
    vimeoId: "1099892481",
    contentType: "Lecture",
    duration: "09:00",
    daysAgo: 1,
  },
  {
    id: 21,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Free",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "824804225",
    contentType: "Live",
    duration: "12:00",
    daysAgo: 4,
  },
  {
    id: 22,
    type: "Disc",
    category: "Hip",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/05.jpg",
    vimeoId: "1100513906",
    contentType: "Case",
    duration: "10:00",
    daysAgo: 2,
  },
  {
    id: 23,
    type: "Disc",
    category: "Hip",
    level: "Advanced",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/07.jpg",
    vimeoId: "1052846854",
    contentType: "Lecture",
    duration: "08:00",
    daysAgo: 1,
  },
  {
    id: 24,
    type: "Disc",
    category: "Hip",
    level: "Advanced",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/03.jpg",
    vimeoId: "1099892481",
    contentType: "Live",
    duration: "13:00",
    daysAgo: 6,
  },
  {
    id: 25,
    type: "Meniscus",
    category: "Hip",
    level: "Beginner",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/05.jpg",
    vimeoId: "1052846854",
    contentType: "Case",
    duration: "11:00",
    daysAgo: 3,
  },
  {
    id: 26,
    type: "Dislocation",
    category: "Ankle",
    level: "Advanced",
    status: "Locked",
    thumbnail: "/assets/images/continue-watch/07.jpg",
    vimeoId: "1099892481",
    contentType: "Lecture",
    duration: "10:00",
    daysAgo: 1,
  },
];

// Assign contentType and same vimeoId to all cards
// cardData.forEach((card, idx) => {
//   card.contentType = contentTypes[idx % contentTypes.length];
//   card.vimeoId = "1100513906";
// });

export default cardData;
