[build]
  # Set Node.js version to a recent LTS version (e.g., 18, 20)
  # Check Node.js LTS releases for the latest stable version.
  # As of late 2024 / early 2025, Node.js 20 LTS is a good choice.

  environment = { NODE_VERSION = "22.18.0" }
